# Generated by Django 5.0.6 on 2024-07-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrokerageAccountType",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("401K", "401k"),
                            ("ROTH 401K", "ROTH 401K"),
                            ("Traditional IRA", "Traditional IRA"),
                            ("Roth IRA", "Roth IRA"),
                            ("HSA", "HSA"),
                            ("SEP IRA", "SEP IRA"),
                            ("Annuity", "Annuity"),
                            ("Defered Compensation", "Defered Compensation"),
                            ("Taxable", "Taxable"),
                            ("RSU", "RSU"),
                            ("ESPP", "ESPP"),
                            ("Trust", "Trust"),
                            ("529", "529"),
                            ("Custodial UTMA", "Custodial UTMA"),
                            ("Custodial UGMA", "Custodial UGMA"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("investment_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentPlatform",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Wells Fargo", "Wells Fargo"),
                            ("Etrade", "Etrade"),
                            ("Fidelity", "Fidelity"),
                            ("Schwab", "Schwab"),
                            ("Prosper", "Prosper"),
                        ],
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        default="brokerage", editable=False, max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brokerage_account_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personal_finance_portfolio.brokerageaccounttype",
                    ),
                ),
                (
                    "investment_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personal_finance_portfolio.investmentplatform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_finance_portfolio.investment",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_finance_portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "investment")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio_investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_finance_portfolio.portfolioinvestment",
                    ),
                ),
            ],
        ),
    ]
