# Generated by Django 5.0.6 on 2024-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentplatform",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
