# Generated by Django 5.0.6 on 2024-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0004_alter_investmentplatform_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentplatform",
            name="name",
            field=models.CharField(
                choices=[
                    ("Wells Fargo", "Wells Fargo"),
                    ("Etrade", "Etrade"),
                    ("Fidelity", "Fidelity"),
                    ("Nationwide", "Nationwide"),
                    ("Schwab", "Schwab"),
                    ("Principal", "Principal"),
                    ("Prosper", "Prosper"),
                ],
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
