# Generated by Django 5.0.6 on 2024-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0005_alter_investmentplatform_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerageaccounttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("401K", "401k"),
                    ("403b", "403b"),
                    ("ROTH 401K", "ROTH 401K"),
                    ("Traditional IRA", "Traditional IRA"),
                    ("Roth IRA", "Roth IRA"),
                    ("HSA", "HSA"),
                    ("SEP IRA", "SEP IRA"),
                    ("Annuity", "Annuity"),
                    ("Defered Compensation", "Defered Compensation"),
                    ("Taxable", "Taxable"),
                    ("RSU", "RSU"),
                    ("ESPP", "ESPP"),
                    ("ESPP & RSU", "ESPP & RSU"),
                    ("Trust", "Trust"),
                    ("529", "529"),
                    ("Custodial UTMA", "Custodial UTMA"),
                    ("Custodial UGMA", "Custodial UGMA"),
                    ("Other", "Other"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
