# Generated by Django 5.0.6 on 2024-07-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0006_alter_brokerageaccounttype_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="symbol",
            new_name="ticker_symbol",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="investment_type",
        ),
        migrations.AddField(
            model_name="investment",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="InvestmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_finance_portfolio.category",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_finance_portfolio.investment",
                    ),
                ),
            ],
            options={
                "unique_together": {("investment", "category")},
            },
        ),
    ]
