# Generated by Django 5.0.6 on 2024-07-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personal_finance_portfolio",
            "0007_category_rename_symbol_investment_ticker_symbol_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "investment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="personal_finance_portfolio.investment",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("dividend_yield", models.DecimalField(decimal_places=2, max_digits=5)),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pe_ratio", models.DecimalField(decimal_places=2, max_digits=5)),
                ("beta", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=("personal_finance_portfolio.investment",),
        ),
    ]
