# Generated by Django 5.0.6 on 2024-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0008_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="categories",
            field=models.ManyToManyField(
                to="personal_finance_portfolio.investmentcategory"
            ),
        ),
    ]
