# Generated by Django 5.0.6 on 2024-07-28 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0009_stock_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="categories",
        ),
    ]
