# Generated by Django 5.0.6 on 2024-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_finance_portfolio", "0011_investment_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Domestic Equity", "Domestic Equity"),
                            ("International Equity", "International Equity"),
                            ("Global Equity", "Global Equity"),
                            ("Government Bonds", "Government Bonds"),
                            ("Corporate Bonds", "Corporate Bonds"),
                            ("Municipal Bonds", "Municipal Bonds"),
                            ("Balanced Funds", "Balanced Funds"),
                            ("Alternative Funds", "Alternative Funds"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeographicFocus",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ASIA", "Asia"),
                            ("Europe", "Europe"),
                            ("Latin America", "Latin America"),
                            ("China", "China"),
                            ("US", "US"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentStyle",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Growth", "Growth"),
                            ("Value", "Value"),
                            ("Blend/Core", "Blend/Core"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectorIndustryFocus",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Healthcare", "Healthcare"),
                            ("Financials", "Financials"),
                            ("Energy", "Energy"),
                            ("Consumer Discretionary", "Consumer Discretionary"),
                            ("Consumer Staples", "Consumer Staples"),
                            ("Utilities", "Utilities"),
                            ("Real Estate", "Real Estate"),
                            ("Industrials", "Industrials"),
                            ("Materials", "Materials"),
                            ("Telecommunications", "Telecommunications"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
