# Generated by Django 5.0.6 on 2024-11-02 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personal_finance_portfolio",
            "0012_assetclass_geographicfocus_investmentstyle_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Transaction fees, commissions, etc.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional transaction details"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for tax system reference",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to related transaction (e.g., dividend to reinvestment)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personal_finance_portfolio.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="settlement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_source",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Direct Purchase"),
                    ("REINVESTMENT", "Dividend Reinvestment"),
                    ("CORPORATE_ACTION", "Corporate Action"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                default="PURCHASE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="portfolio_investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="personal_finance_portfolio.portfolioinvestment",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price per unit", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(help_text="Quantity affected by the transaction"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("BUY", "Buy"),
                    ("SELL", "Sell"),
                    ("DIVIDEND", "Dividend"),
                    ("SPLIT", "Stock Split"),
                    ("TRANSFER", "Transfer"),
                    ("FEE", "Fee"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio_investment", "transaction_date"],
                name="personal_fi_portfol_f726d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="personal_fi_transac_acbad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference_id"], name="personal_fi_referen_4e08ee_idx"
            ),
        ),
    ]
